# Generated by Django 4.2.4 on 2023-09-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('descripccion', models.TextField(blank=True)),
                ('Estado', models.CharField(max_length=200)),
            ],
        ),
    ]
