# Generated by Django 4.2.4 on 2023-09-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TareasAsig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='Estado',
            field=models.CharField(choices=[('proceso', 'Proceso'), ('Pendiente', 'Pendiente'), ('terminada', 'Terminada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='tipo',
            field=models.CharField(choices=[('Tarea', 'Tarea'), ('trabajo', 'Trabajo'), ('evalucion', 'Evaluacion')], max_length=15),
        ),
    ]
